version: '3'
services:
  src:
    container_name: odoo15-src
    image: odoo:15.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo15-src-data:/var/lib/odoo
      - ./odoo.conf:/etc/odoo/odoo.conf
      - ./owl-bookstore:/mnt/extra-addons
  db:
    container_name: odoo15-db
    image: postgres:12
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5542:5432"
    volumes:
      - odoo15-db-data:/var/lib/postgresql/data/pgdata
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:6.1
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@nasser.cm
      PGADMIN_DEFAULT_PASSWORD: 123
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8099:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - "db:psql-schooler-server"
volumes:
  odoo15-src-data:
  odoo15-db-data:
  pgadmin-data:
